# Use root/example as user/password credentials
version: '3.1'

services:
  go:
    image: api-docker
    build: .
    ports:
      - "6060:8000"
    depends_on:
      - db

  db:
    image: mariadb-docker
    # restart: always
    # environment:
    #    MYSQL_ROOT_PASSWORD: test